# Generated by Django 3.2.3 on 2021-08-24 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200)),
                ('image_file', models.FileField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_title', models.CharField(max_length=200)),
                ('skill_percent', models.IntegerField()),
                ('skill_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Techno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techno_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_title', models.CharField(max_length=200)),
                ('study_description', models.TextField(null=True)),
                ('study_city', models.CharField(max_length=200)),
                ('study_country', models.CharField(max_length=100)),
                ('study_start', models.DateTimeField(verbose_name='Date de début')),
                ('study_end', models.DateTimeField(verbose_name='Date de fin')),
                ('study_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.image')),
                ('study_skill', models.ManyToManyField(null=True, to='portfolio.Skill')),
                ('study_techno', models.ManyToManyField(null=True, to='portfolio.Techno')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_description', models.TextField(null=True)),
                ('project_link', models.URLField(max_length=300, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='Date de création')),
                ('project_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.image')),
                ('project_skill', models.ManyToManyField(null=True, to='portfolio.Skill')),
                ('project_techno', models.ManyToManyField(to='portfolio.Techno')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=200)),
                ('work_description', models.TextField(null=True)),
                ('work_city', models.CharField(max_length=200)),
                ('work_country', models.CharField(max_length=100)),
                ('work_start', models.DateTimeField(null=True, verbose_name='Date de début')),
                ('work_end', models.DateTimeField(verbose_name='Date de fin')),
                ('work_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.image')),
                ('work_skill', models.ManyToManyField(null=True, to='portfolio.Skill')),
                ('work_techno', models.ManyToManyField(null=True, to='portfolio.Techno')),
            ],
        ),
    ]
