# Generated by Django 3.2.3 on 2021-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='work_skill',
            field=models.ManyToManyField(to='portfolio.Skill'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='work_techno',
            field=models.ManyToManyField(to='portfolio.Techno'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_skill',
            field=models.ManyToManyField(to='portfolio.Skill'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_skill',
            field=models.ManyToManyField(to='portfolio.Skill'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_techno',
            field=models.ManyToManyField(to='portfolio.Techno'),
        ),
    ]
